config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
      passwords: 'passwords', registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|ru/ do
    devise_for :admin_users, :categories, :wallpapers, :comments, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :users, skip: :omniauth_callbacks
    resources :users, :comments, :activities

    resources :wallpapers do
      resources :comments
      resources :likes, only: [:new, :create, :destroy]
    end

    resources :categories do
      resources :subscriptions, only: [:new, :create, :destroy]
    end

    get ':/locale', to: 'categories#index'
    get 'user/index', to: 'users#index'
    get 'wallpaper/:id/fullsize', to: 'wallpapers#fullsize', as: 'fullsize', method: 'show'

    match 'admin/parsing', to: 'admin/parsing#index', via: [:get, :post]

    root 'categories#index'
    get 'omniauth/:provider', to: 'omniauth#localized', as: :localized_omniauth

    # resources :users do
    #   member do
    #     get 'user/index', to: 'users#index'
    #   end
    # end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/wallpaper.rb
class Wallpaper < ApplicationRecord
  extend FriendlyId

  belongs_to :category, counter_cache: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, :image, :category_id, presence: true

  friendly_id :title, use: :slugged

  mount_uploader :image, ImageUploader

  paginates_per 80
  max_paginates_per 80
end

app/controllers/wallpapers_controller.rb
class WallpapersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :load_categories, only: [:new, :create, :edit, :update]
  before_action :load_wallpaper, only: [:show, :edit, :update, :destroy, :fullsize]

  def index
    @wallpapers = Wallpaper.all.order('likes_count DESC, title').page(params[:wallpapers_page])
  end

  def show; end

  def new
    @wallpaper = Wallpaper.new
  end

  def edit; end

  def create
    @wallpaper = Wallpaper.new(wallpaper_params)
    if @wallpaper.save
      list_for_notification
      redirection
    else
      render :new
    end
  end

  def update
    if @wallpaper.update_attributes(wallpaper_params)
      redirection
    else
      render :edit
    end
  end

  def destroy
    @wallpaper.destroy
    redirection
  end

  def fullsize; end

  def list_for_notification
    emails = @wallpaper.category.users.pluck(:email)
    emails.each { |email| UserMailer.with(category: @wallpaper.category).new_wallpaper_at_subs_category(email).deliver_now }
  end

  private

  def redirection
    unless request&.referer&.include?("/#{I18n.locale}/admin/parsing")
      current_admin_user ? redirect_to(admin_wallpapers_path) : redirect_to(wallpapers_path)
    end
  end

  def wallpaper_params
    params.require(:wallpaper).permit(:title, :category_id, :image, :image_cache, :remote_image_url)
  end

  def load_wallpaper
    @wallpaper = Wallpaper.friendly.find(params[:id])
  end

  def load_categories
    @categories = Category.includes(:subscriptions).all
  end

  def like_proc
    @wallpaper.likes.new
  end
end

app/helpers/wallpapers_helper.rb
module WallpapersHelper
  def exist_like?(obj)
    @like = current_user&.likes&.find_by wallpaper: obj
  end
end

app/views/wallpapers/_editform.html.haml
= form_for @wallpaper do |f|
  .row
    %table
      %tbody
        %tr
          %td
            = f.label :title, 'Image name:'
          %td
            = f.text_field :title
        %tr
          %td
            = f.label :category, 'Category: '
          %td
            = f.collection_select :category_id, @categories, :id, :name
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/wallpapers/_form.html.haml
= form_for @wallpaper do |f|
  .row
    %table
      %tbody
        %tr
          %td
            = f.label :title, 'Image name:'
          %td
            = f.text_field :title
        %tr
          %td
            = f.label :category, 'Category: '
          %td
            = f.collection_select :category_id, @categories, :id, :name
        %tr
          %td
            = f.label :image, 'Local file:'
          %td
            = f.file_field :image
            = f.hidden_field :image_cache
        %tr
          %td{ colspan: '2' }
            %span Choose one of
            %button.btn.btn-sm.btn-warning
              = fa_icon 'arrows-v'
        %tr
          %td
            = f.label :remote_image_url, 'Image-link URL:'
          %td
            = f.text_field :remote_image_url
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/wallpapers/edit.html.haml
.d-flex.mt-1.justify-content-center
  .card{style: "width: 26rem;"}
    %img.img-fluid{ alt: 'wallpaper', src: @wallpaper.image.thumb.url }
    .caption{ style:'text-align: center;' }
      = @wallpaper.title
    .card-body
      .info_text_block
        Edit wallpaper and then press "Save", or get
        = link_to 'back', wallpapers_path
        to Gallery list
      %br/
      = render 'editform', wallpaper: @wallpaper

app/views/wallpapers/fullsize.html.haml
/page is overabundant, but working, and it's an example of hand written route. Should be deleted in future.
.row
  .col-xs-12
    = link_to 'Back', wallpaper_path, class: "btn btn-default"
  %br/
  .col-xs-12
    = image_tag(@wallpaper.image.url, alt: 'Image')

app/views/wallpapers/index.html.haml
.main_nav_bar
  #menu-overlay-btn.btn.btn-primary
    = fa_icon 'navicon'
  #log-overlay-btn.btn.btn-primary
    = fa_icon 'key'
.page_content
  %tile_block
    .row.justify-content-center
      - @wallpapers.each do |wallpaper|
        .col.col-12.col-xs-6.col-md-6.col-lg-4.col-xl-3
          = link_to wallpaper.image.url, target: '_blank' do
            .img-overlaid
              %img.img-fluid{ alt: 'wallpaper', src: wallpaper.image.thumb.url }
              #tile.overlay.align-content-space-around
                %p
                  = wallpaper.title
                = link_to 'Correct', edit_wallpaper_path(wallpaper)
                = link_to 'Comment', wallpaper_path(wallpaper)
                - if wallpaper.category
                  = link_to "Watch category: #{wallpaper.category.name}", category_path(wallpaper.category)
                - else
                  %p
                    Uncategorized
    .row
      = paginate @wallpapers, param_name: 'wallpapers_page'

app/views/wallpapers/new.html.haml
.d-flex.mt-1.justify-content-center
  .card{style: "width: 26rem;"}
    .card-body
      .info_text_block
        %span
          Fill the fields and then press "Save", or get
        - if request.referer
          = link_to 'back', request.referrer
        - else
          = link_to 'back', wallpapers_path
        %span
          to Gallery list
      %br/
      = render 'form', wallpaper: @wallpaper

app/views/wallpapers/show.html.haml
.main_nav_bar
  #menu-overlay-btn.btn.btn-primary
    = fa_icon 'navicon'
  #log-overlay-btn.btn.btn-primary
    = fa_icon 'key'
  #mid-overlay-btn.btn.btn-primary
    = fa_icon 'chevron-down'
  .mid-overlay
    .overlay
      - if request.referer && request.referer != request.original_url
        = link_to 'Back', request.referrer, id: 'back'
      - else
        = link_to 'Back', wallpapers_path, id: 'back'
      - if @wallpaper.category
        = link_to "Watch category: #{@wallpaper.category.name}", category_path(@wallpaper.category)
      - else
        %p
          Uncategorized
.page_content
  .d-flex.mt-5.justify-content-center
    %tile_block
      .row
        = link_to @wallpaper.image.url, target: '_blank' do
          .img-overlaid
            %img.img-fluid{ alt: 'wallpaper', src: @wallpaper.image.thumb.url }
            #tile.overlay.align-content-space-around
              %button.btn.btn-sm.btn-info.disabled
                = fa_icon 'heart'
                %lcount
                  = @wallpaper.likes_count
              - if current_user
                - if exist_like?(@wallpaper)
                  = link_to (fa_icon 'thumbs-down'), new_wallpaper_like_path(@wallpaper), class: "btn btn-sm btn-secondary", remote: true, id: 'like'
                - else
                  = link_to (fa_icon 'thumbs-up'), new_wallpaper_like_path(@wallpaper), class: "btn btn-sm btn-success", remote: true, id: 'like'
  .d-flex.mt-1.justify-content-center
    = render 'comments/form' if current_user.present? || current_admin_user.present?
  .d-flex.justify-content-center.mt-1.flex-column.align-items-center
    = render @wallpaper.comments.order('created_at desc')