config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
      passwords: 'passwords', registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|ru/ do
    devise_for :admin_users, :categories, :wallpapers, :comments, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :users, skip: :omniauth_callbacks
    resources :users, :comments, :activities

    resources :wallpapers do
      resources :comments
      resources :likes, only: [:new, :create, :destroy]
    end

    resources :categories do
      resources :subscriptions, only: [:new, :create, :destroy]
    end

    get ':/locale', to: 'categories#index'
    get 'user/index', to: 'users#index'
    get 'wallpaper/:id/fullsize', to: 'wallpapers#fullsize', as: 'fullsize', method: 'show'

    match 'admin/parsing', to: 'admin/parsing#index', via: [:get, :post]

    root 'categories#index'
    get 'omniauth/:provider', to: 'omniauth#localized', as: :localized_omniauth

    # resources :users do
    #   member do
    #     get 'user/index', to: 'users#index'
    #   end
    # end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId

  has_many :categories, as: :categorized
  has_many :subscriptions, dependent: :destroy
  has_many :follows, through: :subscriptions, source: :category
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :activities, dependent: :nullify

  validates :email, presence: true
  validates :password, confirmation: true, length: { in: 6..20 }, on: :create
  validates :password, confirmation: true, allow_blank: true, on: :update
  validates :email, uniqueness: true
  validates :nickname, length: { in: 1..20 }, allow_blank: true
  validates :nickname, uniqueness: { case_sensitive: false }, allow_blank: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]

  friendly_id :nickname, use: :slugged

  mount_uploader :avatar, AvatarUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.token = auth.credentials.token
      # user.expires = auth.credentials.expires
      # user.expires_at = auth.credentials.expires_at
      # user.refresh_token = auth.credentials.refresh_token
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.google_oauth2_data"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
    end
    redirect_to '/'
  end

  def localized
    # Just save the current locale in the session and redirect to the unscoped path as before
    session[:omniauth_login_locale] = I18n.locale
    redirect_to user_omniauth_authorize_path(params[:provider])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user, only: [:index, :edit, :update, :destroy]

  def index; end

  def edit; end

  def update
    if @user.update_attributes(params.require(:user).permit(:nickname, :avatar, :encrypted_password, :password_confirmation))
      current_admin_user ? redirect_to(admin_user_users_path) : redirect_to(users_path)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def load_user
    @user = User.includes(:subscriptions).find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:nickname, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  .row
    %table
      %tbody
        %tr
          %td
            = f.label :nickname, 'Nickname:'
          %td
            = f.text_field :nickname
        %tr
          %td
            = f.label :avatar, 'Avatar:'
          %td
            = f.file_field :avatar
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/users/edit.html.haml
.d-flex.mt-1.justify-content-center
  .card{style: "width: 20rem;"}
    .card-body
      .info_text_block
        Edit your settings and then press "Save", or get
        = link_to 'back', user_index_path
        to your profile
      %br/
      = render 'form', user: @user

app/views/users/index.html.haml
.main_nav_bar
  #menu-overlay-btn.btn.btn-primary
    = fa_icon 'navicon'
  #log-overlay-btn.btn.btn-primary
    = fa_icon 'key'
  #mid-overlay-btn.btn.btn-primary
    = fa_icon 'chevron-down'
  .mid-overlay
    .overlay
      - if request.referer && request.referer != request.original_url
        = link_to 'Back', request.referrer, id: 'back'
      - else
        = link_to 'Back', categories_path, id: 'back'
      = link_to 'Profile settings', edit_user_path(@user)
      = link_to 'Account deleting', '', { id: 'acc_del', 'data-target' => '#acc_deleting', 'data-toggle' => 'collapse' }
      #acc_deleting.collapse
        .li
          = link_to 'Delete account', user_path(@user), method: :delete,
                    data: { confirm: 'Do you really want to delete your own account?'}
.page_content
  .row.mt-5
    .container-fluid.align-items-center
      .row
        .col-auto.p-0.mr-1
          %div.img-thumbnail
            - if @user.avatar?
              %img.img-fluid{ alt: 'avatar', src: @user.avatar.url }
            - else
              = image_tag 'avatar_default.jpg', alt: 'avatar', class: 'img-fluid'
            .caption
              %span
                Avatar
        .col-auto.other.p-0
          %table.table-bordered.table-striped{ style: 'background-color: #DCDCDC;' }
            %tbody
              %tr
                %td
                  %span
                    Email:
                %td
                  = @user.email
              %tr
                %td
                  %span
                    Nickname:
                - if @user.nickname && !@user.nickname.eql?('')
                  %td
                    = @user.nickname
                - else
                  %td
                    %span User
                    = @user.id
  - if @user.subscriptions.first
    .subscriptions_block
      .row.mt-1
        %alert.alert.alert-success{ role: "alert", style: 'width: 50%; height: 40px;' }
          %span.vertical-center
            Your subscriptions:
      - @user.subscriptions.each do |subs|
        %button.btn.btn-sm.btn-success.disabled.m-1
          %span
            #{ subs.category.name } - last updates
        %tile_block
          .row.justify-content-center
            - subs.category.wallpapers.last(12).reverse.each do |wp|
              .col.col-12.col-xs-6.col-md-6.col-lg-4.col-xl-3
                .img-overlaid
                  = link_to  wallpaper_path(wp), target: '_blank' do
                    %img.img-fluid{ alt: 'recent wallpaper', src: wp.image.thumb.url }
                    #tile.overlay
                      %p
                        = wp.title