config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
      passwords: 'passwords', registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|ru/ do
    devise_for :admin_users, :categories, :wallpapers, :comments, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :users, skip: :omniauth_callbacks
    resources :users, :comments, :activities

    resources :wallpapers do
      resources :comments
      resources :likes, only: [:new, :create, :destroy]
    end

    resources :categories do
      resources :subscriptions, only: [:new, :create, :destroy]
    end

    get ':/locale', to: 'categories#index'
    get 'user/index', to: 'users#index'
    get 'wallpaper/:id/fullsize', to: 'wallpapers#fullsize', as: 'fullsize', method: 'show'

    match 'admin/parsing', to: 'admin/parsing#index', via: [:get, :post]

    root 'categories#index'
    get 'omniauth/:provider', to: 'omniauth#localized', as: :localized_omniauth

    # resources :users do
    #   member do
    #     get 'user/index', to: 'users#index'
    #   end
    # end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId

  belongs_to :categorized, polymorphic: true
  has_many :wallpapers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions

  validates :name, :categorized, presence: true
  validates :name, uniqueness: true

  friendly_id :name, use: :slugged

  paginates_per 6
  max_paginates_per 6
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :load_category, only: [:show, :edit, :update, :destroy]

  class SomethingBad < StandardError

  end

  def index
    @e_categories = Category.all.where(wallpapers_count: 0)
    @categories = Category.all.order('wallpapers_count DESC, name')
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    user = current_admin_user || current_user
    render :new unless user
    category = user.categories.new(category_params)
    if category.save
      flash[:success] = 'Creation successful.'
    else
      flash[:warning] = 'Category has not been saved.'
    end
    redirection
  end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = 'Category parameters have been saved.'
      redirection
    else
      flash[:warning] = 'Category has not been saved.'
      render :edit
    end
  end

  def destroy
    @category.destroy unless @category.locked?
    redirect_to categories_path
  end

  private

  def redirection
    current_admin_user ? redirect_to(admin_categories_path) : redirect_to(categories_path)
  end

  def load_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :locked)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def own?(obj) 
    if current_admin_user
      return true if current_admin_user == obj.categorized && obj.categorized_type == 'AdminUser'
    elsif current_user
      return true if current_user == obj.categorized && obj.categorized_type == 'User'
    else
      false
    end
  end

  def exist_subscription?(obj)
    @subscription = current_user.subscriptions.find_by category: obj
  end
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  = f.label :name, 'Name:'
  = f.text_field :name
  %br/
  .actions
    = f.submit 'Save', class: "btn btn-info", id: 'modal-save'

app/views/categories/_new.html.haml
.modal-header
  .col-auto.mr-auto
    %button.btn.btn-success.disabled
      Creating new category
  .col-auto
    %button.close{"aria-label": "Close", "data-dismiss": "modal", type: "button"}
      ×
.modal-body
  = render 'form', category: @category

app/views/categories/edit.html.haml
.d-flex.mt-1.justify-content-center
  .card{style: "width: 20rem;"}
    .card-body
      .info_text_block
        %span
          Correct category name or get
        = link_to 'back', category_path(@category)
      = render 'form', category: @category

app/views/categories/index.html.haml
.main_nav_bar
  #menu-overlay-btn.btn.btn-primary
    = fa_icon 'navicon'
  #log-overlay-btn.btn.btn-primary
    = fa_icon 'key'
  - if user?
    #mid-overlay-btn.btn.btn-primary
      = fa_icon 'chevron-down'
    .mid-overlay
      .overlay
        = link_to 'New category', new_category_path, { remote: true, "data-toggle": "modal",
                                                        "data-target": "#modal-window", id: 'new_ctg_btn' }
        = link_to 'Empty categories', '', { id: 'empty_ctg_collapse', 'data-target' => '#emp_cat_collapse', 'data-toggle' => 'collapse' }
        #emp_cat_collapse.collapse
          - @e_categories.each do |e_cat|
            - unless e_cat.wallpapers.first
              .li
                = link_to e_cat.name, category_path(e_cat)
.page_content
  %backgr_field
    #carouselBgWp.carousel.slide.carousel-fade{'data-ride' => 'carousel', 'data-pause' => 'false' }
      .carousel-inner
        - @bg_wallpapers.each do |bgw|
          .carousel-item
            %img.d-block{alt: 'bg_wp', src: bgw.image.url}
              .carousel-caption.d-none.d-md-block.align-center
                %strong
                  = link_to 'Watch', wallpaper_path(bgw)
      %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselBgWp", :role => "button"}
        %span.carousel-control-prev-icon{"aria-hidden" => "true"}
        %span.sr-only Previous
      %a.carousel-control-next{"data-slide" => "next", :href => "#carouselBgWp", :role => "button"}
        %span.carousel-control-next-icon{"aria-hidden" => "true"}
        %span.sr-only Next
  %tile_block
    - if Category.first
      .row.justify-content-center
        - @categories.each do |category|
          - if category.wallpapers.first
            .col.col-12.col-xs-6.col-md-6.col-lg-4.col-xl-3
              .img-overlaid
                = link_to category_path(category) do
                  %img.img-fluid{ alt: 'cat_img_sample', src: category.wallpapers.sample.image.thumb.url }
                  #tile.overlay
                    %p
                      = category.name

  //= paginate @categories, param_name: 'categories_page'
#modal-window.modal.hide.fade{"aria-hidden": "true", "aria-labelledby": "modal-windowLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-dialog-centered{role: 'document'}
    .modal-content

app/views/categories/new.html.haml
.d-flex.mt-1.justify-content-center
  .card{style: "width: 20rem;"}
    .card-body
      .info_text_block
        %span
          Enter the name of category you want to create, or get
        - if request.referer
          = link_to 'back', request.referrer
        - else
          = link_to 'back', categories_path
        %span
          to Category list
      %br/
      = render 'form', category: @category

app/views/categories/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal('show');

app/views/categories/show.html.haml
.main_nav_bar
  #menu-overlay-btn.btn.btn-primary
    = fa_icon 'navicon'
  #log-overlay-btn.btn.btn-primary
    = fa_icon 'key'
  - if user?
    #mid-overlay-btn.btn.btn-primary
      = fa_icon 'chevron-down'
    .mid-overlay
      .overlay
        %p
          Category: #{@category.name}
        - if request.referer && request.referer != request.original_url
          = link_to 'Back', request.referrer, id: 'back'
        - else
          = link_to 'Back', categories_path, id: 'back'
        - if current_user
          - if exist_subscription?(@category)
            = link_to (fa_icon 'bell-o'), new_category_subscription_path(@category), class: 'btn btn-danger', remote: true, id: 'follow'
          -else
            = link_to (fa_icon 'bell'), new_category_subscription_path(@category), class: 'btn btn-info', remote: true, id: 'follow'
        - if own?(@category)
          = link_to 'Edit Category name', edit_category_path(@category)
          = link_to 'Delete category', category_path(@category), method: :delete,
            data: { confirm: 'Are you sure?' }
.page_content
  %backgr_field
    #carouselBgWp.carousel.slide.carousel-fade{'data-ride' => 'carousel', 'data-pause' => 'false' }
      .carousel-inner
        - @category.wallpapers.limit(10).each do |ctgwp|
          .carousel-item
            %img.d-block{alt: 'bg_wp', src: ctgwp.image.url}
              .carousel-caption.d-none.d-md-block.align-center
                %strong
                  = link_to 'Watch', wallpaper_path(ctgwp)
      %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselBgWp", :role => "button"}
        %span.carousel-control-prev-icon{"aria-hidden" => "true"}
        %span.sr-only Previous
      %a.carousel-control-next{"data-slide" => "next", :href => "#carouselBgWp", :role => "button"}
        %span.carousel-control-next-icon{"aria-hidden" => "true"}
        %span.sr-only Next
  %tile_block
    .row.justify-content-center
      - @category.wallpapers.each do |wallpaper|
        .col.col-12.col-xs-6.col-md-6.col-lg-4.col-xl-3
          .img-overlaid
            = link_to wallpaper.image.url, target: '_blank' do
              %img.img-fluid{ alt: 'category wallpaper', src: wallpaper.image.thumb.url }
              #tile.overlay
                %p
                  = wallpaper.title
                = link_to 'Correct', edit_wallpaper_path(wallpaper)
                = link_to 'Comment', wallpaper_path(wallpaper)