config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
      passwords: 'passwords', registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|ru/ do
    devise_for :admin_users, :categories, :wallpapers, :comments, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :users, skip: :omniauth_callbacks
    resources :users, :comments, :activities

    resources :wallpapers do
      resources :comments
      resources :likes, only: [:new, :create, :destroy]
    end

    resources :categories do
      resources :subscriptions, only: [:new, :create, :destroy]
    end

    get ':/locale', to: 'categories#index'
    get 'user/index', to: 'users#index'
    get 'wallpaper/:id/fullsize', to: 'wallpapers#fullsize', as: 'fullsize', method: 'show'

    match 'admin/parsing', to: 'admin/parsing#index', via: [:get, :post]

    root 'categories#index'
    get 'omniauth/:provider', to: 'omniauth#localized', as: :localized_omniauth

    # resources :users do
    #   member do
    #     get 'user/index', to: 'users#index'
    #   end
    # end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: "utf-8" }/
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %script{ src: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" }
    %meta{ name: :viewport, content: 'width=device-width, initial-scale=0.8, shrink-to-fit=no' }
  %body
    #sign_in_modal.modal.fade{ 'aria-hidden': 'true', role: 'dialog', tabindex: '-1' }
      .modal-dialog.modal-dialog-centered{ role: 'document'}
        .modal-content
          .modal-header
            .col-auto.mr-auto
              .btn.btn-outline-primary.disabled
                Authorization
            .col-auto
              %button.close{ "aria-label": "Close", "data-dismiss": "modal", type: "button" }
                ×
          .modal-body
            = render "devise/sessions/modal"
    #sign_up_modal.modal.fade{ 'aria-hidden': 'true', role: 'dialog', tabindex: '-1' }
      .modal-dialog.modal-dialog-centered{ role: 'document'}
        .modal-content
          .modal-header
            .col-auto.mr-auto
              .btn.btn-outline-primary.disabled
                Registration
            .col-auto
              %button.close{ "aria-label": "Close", "data-dismiss": "modal", type: "button" }
                ×
          .modal-body
            = render "devise/registrations/modal"
    %header
      .overlay-container
        .left-overlay
          .overlay
            = link_to I18n.t('header.main_bar.categories'), categories_path
            = link_to I18n.t("header.main_bar.top_categories"), '', { id: 'top5categories', 'data-target' => '#top_cat', 'data-toggle' => 'collapse' }
            #top_cat.collapse
              - @top_categories.each do |cat|
                .li
                  = link_to cat.name, category_path(cat)
            = link_to I18n.t('header.main_bar.wallpapers'), wallpapers_path
            = link_to I18n.t('header.main_bar.upload'), new_wallpaper_path
            = link_to I18n.t('header.main_bar.all_comments'), comments_path
        .right-overlay
          .overlay
            - if user_signed_in?
              %p
                = I18n.t("header.main_page_welcome", email: current_user.email)
              = link_to I18n.t('active_admin.devise.profile'), user_index_path
              = link_to I18n.t('active_admin.devise.links.sign_out'), destroy_user_session_path, method: :delete
            - else
              = link_to(user_google_oauth2_omniauth_authorize_path) do
                = fa_icon 'google'
                %span
                  Authorization
              = link_to I18n.t('active_admin.devise.links.sign_in'), '', { id: 'login_modal', 'data-target': '#sign_in_modal', 'data-toggle': 'modal' }
              = link_to I18n.t("active_admin.devise.links.sign_up"), '', { id: 'sign_up_modal', 'data-target': '#sign_up_modal', 'data-toggle': 'modal' }
              //, new_user_registration_path, id: 'sign_up'
            = link_to I18n.t("header.localization"), '', { id: 'localization', 'data-target' => '#locale', 'data-toggle' => 'collapse' }
            #locale.collapse
              .li
                = link_to 'En', {locale: :en}, {style: 'color: yellow !important;'}
              .li
                = link_to 'Ru', {locale: :ru}, {style: 'color: yellow !important;'}

    .content
      = yield

    %footer
      - flash.each do |key, value|
        %div{class: "alert alert-#{key} alert-dismissible fade show", role: "alert" }
          %strong.vertical-center
            = value
          %button.vertical-center.close{ "aria-label": "Close", "data-dismiss": "alert", type: "button", style: 'top: 50%;' }
            %span{ "aria-hidden": "true" } ×